export const sample_foods = [
  {
    id: '1',
    name: 'Alphanso Mango Cake',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'Alphanso-Mango-Cake.jpg',
    tags: ['Cake','Mango'],
  },
  {
    id: '2',
    name: 'American Almond Chocolate Cake',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'American-Almond-Chocolate-Cake.jpg',
    tags: ['Cake','Almond'],
  },
  {
    id: '3',
    name: 'Belgium Truffle Bento Cake',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'Belgium-Truffle-Bento-Cake.jpg',
    tags: ['Truffle','Dessert'],
  },
  {
    id: '4',
    name: 'Friendship Theme Cake 2Kg',
    price: 50,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'friendship-theme-cake-2kg.jpg',
    tags: ['Cake'],
  },
  {
    id: '5',
    name: 'Malted ChocolateCake Pastry Cut piece-4',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'Malted-Chocolate-pastry.jpg',
    tags: ['Pastry','Chocolate'],
  },
  {
    id: '6',
    name: 'Chocolate Donut',
    price: 10,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'chocolate-donut.jpg',
    tags: ['Dessert','Chocolate'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'Cake', count: 3 },
  { name: 'Mango', count: 1 },
  { name: 'Almond', count: 1 },
  { name: 'Dessert', count: 2 },
  { name: 'Chocolate', count: 2 },
  { name: 'Pastry', count: 1 },
  { name: 'Truffle', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Tibet',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Chennai',
    isAdmin: true,
  },
  {
    id: 2,
    name: 'admin',
    email: 'admin@gmail.com',
    password: '12345',
    address: 'Erode',
    isAdmin: true,
  },
];
